# Generated by Django 5.1.15 on 2026-01-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('deporte', models.CharField(choices=[('FUT', 'Fútbol'), ('BAL', 'Baloncesto'), ('PAD', 'Pádel')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
