# Generated by Django 5.1.15 on 2026-01-04 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasBaloncesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('rebotes', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_baloncesto', to='usuario.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_baloncesto', to='torneo.torneo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('torneo', 'jugador'), name='unique_torneo_jugador_estadisticas_baloncesto')],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('goles_contra', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_futbol', to='usuario.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_futbol', to='torneo.torneo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('torneo', 'jugador'), name='unique_torneo_jugador_estadisticas_futbol')],
            },
        ),
    ]
