# Generated by Django 5.1.15 on 2026-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasfutbol',
            name='goles_contra',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
