# Generated by Django 5.1.15 on 2026-01-04 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 dígitos seguidos de una letra mayúscula.', regex='^\\d{8}[A-Z]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('es_portero', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='equipo.equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
