# Generated by Django 5.1.15 on 2026-03-11 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('es_portero', True)), fields=('equipo',), name='unique_portero_por_equipo'),
        ),
    ]
