# Generated by Django 5.1.15 on 2026-03-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_jugador_unique_portero_por_equipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jugador',
            name='unique_portero_por_equipo',
        ),
    ]
