# Generated by Django 5.1.15 on 2026-04-06 19:25

from django.db import migrations


def remove_column_if_exists(apps, schema_editor):
    """
    Elimina la columna debe_cambiar_password si existe en la tabla usuario_jugador
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'usuario_jugador' 
            AND COLUMN_NAME = 'debe_cambiar_password'
        """)
        exists = cursor.fetchone()[0]
        
        # Si existe, eliminarla
        if exists:
            cursor.execute("ALTER TABLE usuario_jugador DROP COLUMN debe_cambiar_password")


def add_column_back(apps, schema_editor):
    """
    Función inversa para restaurar la columna (solo si se hace rollback)
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE usuario_jugador 
            ADD COLUMN debe_cambiar_password TINYINT(1) NOT NULL DEFAULT 0
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_jugador_unique_portero_por_equipo'),
    ]

    operations = [
        migrations.RunPython(remove_column_if_exists, add_column_back),
    ]
