# Generated by Django 5.1.15 on 2026-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_accidental_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_password_por_defecto',
            field=models.BooleanField(default=False),
        ),
    ]
