# Generated by Django 5.1.15 on 2026-04-06 19:25

from django.db import migrations, models


def add_column_if_not_exists(apps, schema_editor):
    """
    Añade la columna tiene_password_por_defecto si no existe en la tabla usuario_jugador
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'usuario_jugador' 
            AND COLUMN_NAME = 'tiene_password_por_defecto'
        """)
        exists = cursor.fetchone()[0]
        
        # Si no existe, crearla
        if not exists:
            cursor.execute("""
                ALTER TABLE usuario_jugador 
                ADD COLUMN tiene_password_por_defecto TINYINT(1) NOT NULL DEFAULT 0
            """)


def remove_column(apps, schema_editor):
    """
    Función inversa para eliminar la columna (solo si se hace rollback)
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE usuario_jugador DROP COLUMN tiene_password_por_defecto")


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_accidental_column'),
    ]

    operations = [
        migrations.RunPython(add_column_if_not_exists, remove_column),
    ]
