# Generated by Django 5.1.15 on 2026-01-04 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rondas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('max_equipos', models.PositiveIntegerField()),
                ('deporte', models.CharField(choices=[('FUT', 'Fútbol'), ('BAL', 'Baloncesto'), ('PAD', 'Pádel')], max_length=3)),
                ('tipo', models.CharField(choices=[('LIG', 'Liga'), ('ELI', 'Eliminatoria'), ('ELG', 'Eliminatoria con Fase de Grupos')], max_length=3)),
                ('playoffs', models.BooleanField(default=False)),
                ('n_equipos_playoffs', models.PositiveIntegerField(null=True)),
                ('descenso', models.BooleanField(default=False)),
                ('n_equipos_descenso', models.PositiveIntegerField(null=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_ganados', to='equipo.equipo')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneos', to='usuario.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_jornada', models.PositiveIntegerField()),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='EliminatoriaGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clasificados_grupo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('n_grupos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('eliminatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatoria_grupos', to='torneo.eliminatoria')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatoria_grupos', to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='eliminatoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias', to='torneo.torneo'),
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(default='GENERAL', max_length=20)),
                ('posicion', models.PositiveIntegerField()),
                ('puntos', models.IntegerField(default=0)),
                ('victorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('anotacion_favor', models.PositiveIntegerField(default=0)),
                ('anotacion_contra', models.PositiveIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='equipo.equipo')),
                ('eliminatoria_grupos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='torneo.eliminatoriagrupos')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='TorneoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_torneos', to='equipo.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo_equipos', to='torneo.torneo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('n_equipos_playoffs__isnull', False), ('playoffs', True)), models.Q(('n_equipos_playoffs__isnull', True), ('playoffs', False)), _connector='OR'), name='torneo_n_equipos_playoffs_solo_si_playoffs_true'),
        ),
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('descenso', True), ('n_equipos_descenso__isnull', False)), models.Q(('descenso', False), ('n_equipos_descenso__isnull', True)), _connector='OR'), name='torneo_n_equipos_descenso_solo_si_descenso_true'),
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(fields=('torneo', 'n_jornada'), name='unique_torneo_n_jornada'),
        ),
        migrations.AddConstraint(
            model_name='eliminatoriagrupos',
            constraint=models.UniqueConstraint(fields=('torneo',), name='unique_torneo_eliminatoria_grupos'),
        ),
        migrations.AddConstraint(
            model_name='eliminatoria',
            constraint=models.UniqueConstraint(fields=('torneo',), name='unique_torneo_eliminatoria'),
        ),
        migrations.AddConstraint(
            model_name='clasificacion',
            constraint=models.UniqueConstraint(fields=('torneo', 'grupo', 'equipo'), name='uq_clasif_torneo_grupo_equipo'),
        ),
        migrations.AddConstraint(
            model_name='clasificacion',
            constraint=models.UniqueConstraint(fields=('torneo', 'grupo', 'posicion'), name='uq_clasif_torneo_grupo_posicion'),
        ),
        migrations.AddConstraint(
            model_name='torneoequipo',
            constraint=models.UniqueConstraint(fields=('torneo', 'equipo'), name='unique_torneo_equipo'),
        ),
    ]
