# Generated by Django 5.1.15 on 2026-01-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clasificacion',
            name='uq_clasif_torneo_grupo_equipo',
        ),
        migrations.RemoveConstraint(
            model_name='clasificacion',
            name='uq_clasif_torneo_grupo_posicion',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='torneo',
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='torneo_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='torneo.torneoequipo'),
        ),
        migrations.AddConstraint(
            model_name='clasificacion',
            constraint=models.UniqueConstraint(fields=('torneo_equipo', 'grupo'), name='uq_clasif_torneo_grupo_equipo'),
        ),
    ]
