# Generated by Django 5.1.15 on 2026-01-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_remove_clasificacion_uq_clasif_torneo_grupo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='torneo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='torneo.torneoequipo'),
        ),
    ]
