# Generated by Django 5.1.15 on 2026-02-08 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_alter_eliminatoriagrupos_n_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminatoriagrupos',
            name='n_grupos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
