# Generated by Django 5.1.15 on 2026-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_alter_eliminatoriagrupos_n_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='anotacion_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='anotacion_favor',
            field=models.IntegerField(default=0),
        ),
    ]
