# Generated by Django 5.1.15 on 2026-02-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_alter_clasificacion_anotacion_contra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminatoriagrupos',
            name='eliminatoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminatoria_grupos', to='torneo.eliminatoria'),
        ),
    ]
