# Generated by Django 5.1.15 on 2026-02-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_alter_eliminatoriagrupos_eliminatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminatoriagrupos',
            name='eliminatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminatoria_grupos', to='torneo.eliminatoria'),
        ),
    ]
