# Generated by Django 5.1.15 on 2026-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_alter_eliminatoriagrupos_eliminatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneoequipo',
            name='nivel',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], null=True),
        ),
    ]
