# Generated by Django 5.1.15 on 2026-01-04 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(blank=True, choices=[('16AV', 'Dieciseisavos de Final'), ('8AV', 'Octavos de Final'), ('CUA', 'Cuartos de Final'), ('SEM', 'Semifinal'), ('FIN', 'Final')], max_length=4, null=True)),
                ('anotacion_local', models.PositiveIntegerField(blank=True, null=True)),
                ('anotacion_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_local_1', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_visitante_1', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_local_2', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_visitante_2', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_local_3', models.PositiveIntegerField(blank=True, null=True)),
                ('juegos_visitante_3', models.PositiveIntegerField(blank=True, null=True)),
                ('eliminatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='torneo.eliminatoria')),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_local', to='equipo.equipo')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_visitante', to='equipo.equipo')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_ganados', to='equipo.equipo')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='torneo.jornada')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('eliminatoria__isnull', False), ('jornada__isnull', True)), models.Q(('eliminatoria__isnull', True), ('jornada__isnull', False)), _connector='OR'), name='enfrentamiento_eliminatoria_o_jornada'), models.CheckConstraint(condition=models.Q(('equipo_local', models.F('equipo_visitante')), _negated=True), name='enfrentamiento_equipo_local_distinto_visitante'), models.CheckConstraint(condition=models.Q(('ganador__isnull', True), ('ganador', models.F('equipo_local')), ('ganador', models.F('equipo_visitante')), _connector='OR'), name='enfrentamiento_ganador_local_o_visitante')],
            },
        ),
    ]
