# Generated by Django 5.1.15 on 2026-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfrentamiento', '0002_estadisticasenfrentamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticasenfrentamiento',
            name='guardado',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
