# Generated by Django 5.1.15 on 2026-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfrentamiento', '0003_estadisticasenfrentamiento_guardado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasenfrentamiento',
            name='guardado',
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='guardado',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
