# Generated by Django 5.1.15 on 2026-02-03 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfrentamiento', '0004_remove_estadisticasenfrentamiento_guardado_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfrentamiento',
            name='guardado',
        ),
        migrations.CreateModel(
            name='GuardadoEnfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadistica_futbol', models.CharField(blank=True, choices=[('GOL', 'Goles'), ('ASI', 'Asistencias')], max_length=3, null=True)),
                ('estadistica_baloncesto', models.CharField(blank=True, choices=[('PTS', 'Puntos'), ('REB', 'Rebotes'), ('ASI', 'Asistencias')], max_length=3, null=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='enfrentamiento.enfrentamiento')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados_enfrentamientos', to='usuario.jugador')),
            ],
        ),
    ]
