# Generated by Django 5.1.15 on 2026-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfrentamiento', '0005_remove_enfrentamiento_guardado_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estadisticasenfrentamiento',
            constraint=models.UniqueConstraint(fields=('enfrentamiento', 'jugador', 'estadistica_futbol', 'estadistica_baloncesto'), name='unique_estadistica_enfrentamiento_jugador_tipo'),
        ),
        migrations.AddConstraint(
            model_name='guardadoenfrentamiento',
            constraint=models.UniqueConstraint(fields=('enfrentamiento', 'jugador', 'estadistica_futbol', 'estadistica_baloncesto'), name='unique_estadistica_enfrentamiento_guardado_jugador_tipo'),
        ),
    ]
