# Generated by Django 5.1.15 on 2026-02-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfrentamiento', '0006_estadisticasenfrentamiento_unique_estadistica_enfrentamiento_jugador_tipo_and_more'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='prev_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_siguientes_local', to='enfrentamiento.enfrentamiento'),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='prev_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_siguientes_visitante', to='enfrentamiento.enfrentamiento'),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_ganador', to='equipo.equipo'),
        ),
    ]
